# These are supported funding model platforms

github: [dinde451]
patreon: https://patreon.com/user?u=92395499&utm_medium=unknown&utm_source=join_link&utm_campaign=creatorshare_creator&utm_content=copyLink
